config/routes.rb
Rails.application.routes.draw do
  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  devise_for :users
  resources :posts, concerns: :paginatable

  root 'posts#index'
  get '/login/vk' => 'vks#new'
  resources :vks

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)

    if user.admin? # role_id=1 is admin
      can :manage, :all
    else
      can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :rememberable,
         :trackable,
         :validatable

  def admin?
    role_id == 1
  end
end

app/models/vk.rb
class Vk < ActiveRecord::Base
end

app/controllers/application_controller.rb
require 'application_responder'

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  self.responder = AppResponder
  respond_to :html, :js, :json

  protected

  def after_sign_in_path_for(resource)
    root_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.page(params[:page]).per(6)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    respond_with(@post)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.save

    respond_with(@post)
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @post.update(post_params)

    respond_with(@post)
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy

    respond_with(@post)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    attrs = %w(title body user_id image remote_image_url)
    params.require(:post).permit(attrs)
  end
end

app/controllers/vks_controller.rb
class VksController < ApplicationController
  def new
    @vk = Vk.new
  end

  def create
    @vk = Vk.new(vk_params)
    @vk.save

    redirect_to '/'
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def vk_params
    params.require(:vk).permit(:login, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vk_helper.rb
module VkHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Sevdol
    = stylesheet_link_tag    'application', media: 'all'
    = csrf_meta_tags
  %body
    .container
      / Static navbar
      %nav.navbar.navbar-default{role: 'navigation'}
        .navbar-header
          %button.navbar-toggle{'data-target' => '.navbar-collapse', 'data-toggle' => 'collapse', type: 'button'}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "My Website", root_path, class: 'navbar-brand'
        .navbar-collapse.collapse
          %ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              %li
                = link_to "Выйти, #{current_user.email}", destroy_user_session_path, method: :delete
            - else
              %li
                = link_to 'Войти с помощью ВК', login_vk_path
              %li
                = link_to 'Войти', new_user_session_path
        / /.nav-collapse
      %div
        - if flash[:notice]
          .alert.alert-success= flash[:notice]
        - if flash[:alert]
          .alert.alert-danger= flash[:alert]
        = yield
= javascript_include_tag 'application'

app/views/posts/_form.html.haml
= form_for @post, :html => {:multipart => true} do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :user_id
    = f.number_field :user_id
  %p
  .field
    = f.file_field :image
  %p
  .field
    = f.label :remote_image_url, 'or image URL'
    = f.text_field :remote_image_url
  .actions
    = f.submit 'Save'

app/views/posts/_modal.html.haml
#modal_post.modal.fade
  .modal-dialog
    .modal-content
      .modal-body
        %button.close#closebtn{ aria: { hidden: true }, data: { dismiss: :modal }, type: 'button' } ×
        = image_tag(@post.image_url.to_s, class: 'modal-image')

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%h1 Галлерея

- @posts.each_slice(3) do |posts_row|
  .row
    -posts_row.each do |post|
      .col-xs-6.col-md-4
        .thumbnail
          = link_to image_tag(post.image_url(:thumb).to_s), post, id: 'image', remote: true
          .caption
            %h3= post.title
            %p= post.body
            %p
              = link_to 'Посмотреть', post
              - if can? :edit, post
                = link_to 'Редактировать', edit_post_path(post)
              - if can? :delete, post
                = link_to 'Удалить', post, method: :delete, data: { confirm: 'Are you sure?' }
-if can? :create, @post
  = link_to 'New Post', new_post_path

%p= paginate @posts, theme: 'twitter-bootstrap-3'

//modal-window
#modal_post.modal.fade
  .modal-dialog
    .modal-content
      .modal-body
        %button.close#closebtn{ aria: { hidden: true }, data: { dismiss: :modal }, type: 'button' } ×

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.haml
%p
  %b Image:
  = link_to image_tag(@post.image_url(:thumb).to_s), '#', id: 'image'
%p
  %b Title:
  = @post.title
%p
  %b Body:
  = @post.body
%p
  %b User:
  = @post.user_id
- if can? :edit, @post
  = link_to 'Edit', edit_post_path(@post)
  \|
= link_to 'Back', posts_path
= render 'modal'

app/views/posts/show.js.erb
$("<%= escape_javascript(image_tag(@post.image_url.to_s, class: 'modal-image')) %>").appendTo('.modal-body');
$('#modal_post').modal('show');

$('body').on('hidden.bs.modal', '.modal', function () {
  $('.modal-image').remove();
});

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/vks/new.html.haml
= form_for @vk do |f|
  .field
    = f.label :login, class: { color: '#45688E' }
    = f.text_field :login, class: 'form-control', placeholder: 'login'
  %br
  .field
    = f.label :password
    = f.text_field :password, class: 'form-control', placeholder: 'login'
  %br
  .actions
    = f.button 'Log In', class: 'btn btn-primary'